### ISSUE TITLE
Connection Lost: Invalid Player Data

### ISSUE THREAD

**Issue by seraphean** [apace100/origins-fabric#397] opened 2021-07-27 07:05 UTC
what it says in the title, getting a connection error "Connection Lost: Invalid Player Data" when adding origins to an existing singleplayer world.

steps to reproduce:
1. create singleplayer world without origins installed
2. quit game and install origins
3. try to enter existing world
4. lose connection and get booted back to multiplayer servers list

i don't think it's a compatibility issue as creating a fresh world with origins installed works fine, but here's a list of other mods installed, just in case:
adorn
axolotl item fix
bedspreads
better biome blend
craftpresence 
custom portals
debrand
disable custom worlds advice
dynamic fps
dynamic music
ears
fabric language kotlin
flesh2leather
illuminations
infinityfix
inmis
lapis reserve
mod menu
more axolotl variants
music duration reducer
optifabric + optifine
origins:classes
pling
smoothboot
snow under trees
the aether
trinkets

**Comment by apace100** [comment] 2021-07-27 08:07
Hi, I couldn't reproduce this. Following the steps doesn't do anything special, it works as intended: I get to choose an origin once I join the previously created world with Origins now installed.
For reference, I was using Fabric API 0.37.0 and Origins 1.0.3

**Comment by swift2plunder** [comment] 2021-08-01 00:27
My spouse is currently having this issue. World created in Minecraft 1.17, Origins 1.0.2, Fabric API 0.36.0 then updated to Minecraft 1.17.1, Origins 1.0.3, and Fabric API 0.37.1. The issue didn't appear at first launch with the updated software, so I'm not confident that I can duplicate it

**Comment by deftesthawk** [comment] 2021-08-09 13:05
After spending a lot of time testing I have come to the conclusion that origins doesn't play well with other mods when you have shaders enabled as I'm getting the same issue when I have Iris shaders installed instead of optifine. Whenever I put stuff in my inventory from multiple mods with shaders enabled and origins installed reloading the world will cause this error to appear

**Comment by itsdinkd** [comment] 2021-09-13 18:55
Try creating the world, exiting minecraft, and then joining that same world again. You'll recreate this issue.

**Comment by deftesthawk** [comment] 2021-09-13 19:34
> Try creating the world, exiting minecraft, and then joining that same world again. You'll recreate this issue.

A fix was found with help of another person, here’s a link to the fix:

https://github.com/apace100/origins-fabric/issues/409#issuecomment-903277269

**Comment by apace100** [comment] 2021-10-02 20:19
Should be fixed with the newest version (1.1.0, released yesterday)

**Closed as completed by apace100** 2021-10-02 20:19 UTC
