### ISSUE TITLE
phantom taking damage inside blocks

### ISSUE THREAD

**Issue by MajdSH-dev** [apace100/origins-fabric#485] opened 2022-01-08 15:28 UTC
in 1.18.1 there is a problem that cause the phantom form to take damage when inside a blocks

**Comment by apace100** [comment] 2022-01-09 00:48
It's a current incompatibility with Lithium. Lithium has added a new rule for optimizing entity suffocation checks, which currently causes Phantom (and any other origins with phasing powers) to suffocate while moving through blocks.


To disable this new optimization rule, you can set the value of the `mixin.entity.collisions.suffocation` field inside the `lithium.properties` file from your Minecraft's (or server's) `config` folder to `false`, like so:

```toml
# This is the configuration file for Lithium.
# This file exists for debugging purposes and should not be configured otherwise.
#
# You can find information on editing this file and all the available options here:
# https://github.com/jellysquid3/lithium-fabric/wiki/Configuration-File
#
# By default, this file will be empty except for this notice.
mixin.entity.collisions.suffocation=false
```

**Comment by apace100** [comment] 2022-01-09 00:50
Duplicate of https://github.com/apace100/origins-fabric/issues/473

**Closed as completed by apace100** 2022-01-09 00:50 UTC
Labels: bug, compatibility
