### ISSUE TITLE
Crashes on startup 1.18.1

### ISSUE THREAD

**Issue by YnwLNE** [apace100/origins-fabric#515] opened 2022-03-27 00:41 UTC
Origins has been unresponsive for a while now and it's giving different results every time. It doesn't generate a crash log but here's the latest log

https://pastebin.com/dsxEx5ug

I see spectrum but it was crashing way before that

**Comment by eggohito** [comment] 2022-04-10 01:11
The one you're seeing before the Spectrum conflict issue seems to be TooltipRareness conflicting with Architectury, although it isn't the main cause for the crash. The main cause for the crash is the mixin transformation failure of the `class_1309` (`LivingEntity`) class. It's caused by Spectrum conflicting with Apoli (the power system used by Origins).

I believe the Spectrum conflict issue will be fixed on the next update

**Comment by apace100** [comment] 2022-04-20 13:03
Spectrum and Origins have updated both their versions for 1.18.1 and 1.18.2 to solve this compatibility issue. Please report back if you're still encountering problems.

**Closed as completed by apace100** 2022-04-20 13:03 UTC
