### ISSUE TITLE
Game crashes (1.17)

### ISSUE THREAD

**Issue by Ameliaplayz** [apace100/origins-fabric#360] opened 2021-06-23 05:45 UTC
listed mods
![Screenshot (626)](https://user-images.githubusercontent.com/84192828/123042327-3aca0d80-d429-11eb-828d-010e5b86af13.png)

**Comment by Ameliaplayz** [comment] 2021-06-23 05:45
also no crash report

**Comment by apace100** [comment] 2021-06-30 07:59
You're not using Origins in there. Why are you reporting this here? But if this is the list of _other_ mods you are using, and it crashes when including Origins, it's because of this: https://github.com/apace100/origins-fabric/issues/354

I'm closing this because it's a duplicate of that issue.

**Closed as completed by apace100** 2021-06-30 07:59 UTC
