### ISSUE TITLE
Game crashes when putting on pumpkin as Elytrian.

### ISSUE THREAD

**Issue by BinaryBitGamer** [apace100/origins-fabric#173] opened 2021-03-04 18:26 UTC
I had been on my 1.16.5 origins server, and decided to try and put a pumpkin on. The game crashed.
Here's what I think happened. 
Pumpkins have no armor value, so the game couldn't figure out if it was stronger, or weaker than chainmail, so the game did something that caused a crash.
Mods being used are:
1.Fabric api
2.Literally chunk loader
3.Optifine
4.Optifabric
5.Origins
6.Origins Classes
7.Replay mod
[latest.log](https://github.com/apace100/origins-fabric/files/6085816/latest.log)
Also, I have never posted a bug report so I don't know what I am doing.

**Comment by apace100** [comment] 2021-03-04 23:17
Hi. I couldn't reproduce this on a clean client/server with just Fabric API and just Origins or Origins and Origins: Classes. Therefore this must be some compatibility issue. (I tried equipping a carved pumpkin as an Elytrian with all three possible methods: regular, shift-click and dispenser)

If you could try removing the other mods one after another from your mods folder and testing the behavior again, in order to see which mod causes the issue, that would be very helpful. Thanks.

**Comment by BinaryBitGamer** [comment] 2021-03-05 02:04
Okay, I'll go through each mod to see which one caused it.

**Comment by BinaryBitGamer** [comment] 2021-03-05 13:45
Okay, so it looks like even after I take out the other mods the game still crashes.  
[latest.log](https://github.com/apace100/origins-fabric/files/6090830/latest.log)

Here is the error the launcher gives me

The game crashed whilst container click
Error: java.lang.NullPointerException: Container click
Exit Code: -1

**Comment by xCryptx** [comment] 2021-03-06 10:44
My personal issue happened with Origins and Origins Classes. As a specific Origin, you are unable to put on certain armors below a specific class. If you try to put it on any armor slots, you get kicked from the server or crash out with a Container Click pointer issue. May be something for trinkets as well, not sure.

**Comment by Tacodude7729** [comment] 2021-03-07 01:28
This looks like the same crash as #107 (Fixed in #180). Are you trying to put a pumpkin or a carved pumpkin on?

**Comment by BinaryBitGamer** [comment] 2021-03-07 03:57
Yes, that is exactly what I am trying to do. I'm very new to posting bug reports, so I have no clue what I am doing.

**Comment by apace100** [comment] 2021-03-22 16:20
@BinaryBitGamer Could you confirm that this bug was fixed in version 0.6.0 (or above)?

**Comment by apace100** [comment] 2021-04-18 15:14
Closing this because of no reply. Comment if the problem still persist please.

**Closed by apace100** 2021-04-18 15:14 UTC
Labels: bug, compatibility
