### ISSUE TITLE
Exception in server tick loop crash when updating my origins datapack to 1.19

### ISSUE THREAD

**Issue by MichaelJackson23** [apace100/origins-fabric#581] opened 2022-07-30 18:24 UTC
I've been making origins on 1.18 for a while now and when it was time to update them to 1.19 this strange crash started happening

[crash-2022-07-30_13.09.45-server.txt](https://github.com/apace100/origins-fabric/files/9227077/crash-2022-07-30_13.09.45-server.txt)

Any info on this crash would be incredibly helpful

**Comment by notabirb1** [comment] 2022-07-31 17:25
I'm getting this crash as well, this only happened once I updated to 1.19.1.

**Comment by ghost** [comment] 2022-08-01 04:15
Same issue 
[crash-2022-07-31_21.13.31-server.txt](https://github.com/apace100/origins-fabric/files/9230819/crash-2022-07-31_21.13.31-server.txt)
was loading custom datapacks for origins mod

**Comment by apace100** [comment] 2022-08-01 19:43
Origins is not compatible with 1.19.1 - the file on CF is not marked as compatible with 1.19.1.
The problem is a changed method in the command system, making `execute_command` actions cause this crash.

**Comment by notabirb1** [comment] 2022-08-02 03:18
You may want to update the listing on Modrinth then, as it is listed as 1.19.1-compatible on Modrinth (which is why I assumed it would work).

**Comment by ghost** [comment] 2022-08-15 15:45
> You may want to update the listing on Modrinth then, as it is listed as 1.19.1-compatible on Modrinth (which is why I assumed it would work).

It does not work. Having the same issue here. Is there any ETA for a fix?

**Comment by Not-February** [comment] 2022-09-14 10:38
A [comment on Curse](https://www.curseforge.com/minecraft/mc-mods/origins?comment=3623) leads me to wonder whether this is caused specifically by selected origins that alter player size. It would certainly match up with my own experience getting this crash, as all of the origins I'd personally tried from Bucolic Origins do indeed have size alterations, but I have yet to test more extensively with origins that don't do anything with the player's size

Could anyone else who has had this issue perhaps clarify what origin datapack/addon they are using/getting the crash with, as well as whether the origin selected that causes the crash alters player size in any way?

Quoting the comment itself for ease of access:

> playing on 1.19.2 works fine but any origin that changes size causes this error, causing any server (singleplayer or dedicated) to crash, yes i have pehkui


> Description: Exception in server tick loopDescription: Exception in server tick loop
> java.lang.NoSuchMethodError: 'int net.minecraft.class_2170.method_9249(net.minecraft.class_2168, java.lang.String)' at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.8) at io.github.apace100.apoli.power.factory.action.EntityActions.lambda$register$15(EntityActions.java:235) at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41) at io.github.apace100.origins.power.OriginsCallbackPower.onChosen(OriginsCallbackPower.java:24) at io.github.apace100.origins.component.OriginComponent.lambda$onChosen$0(OriginComponent.java:49) at java.lang.Iterable.forEach(Iterable.java:75) at io.github.apace100.origins.component.OriginComponent.onChosen(OriginComponent.java:49) at io.github.apace100.origins.networking.ModPacketsC2S.lambda$chooseOrigin$0(ModPacketsC2S.java:50) at net.minecraft.server.ServerTask.run(ServerTask:18) at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:776) at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:159) at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:758) at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:752) at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:140) at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:737) at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:669) at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257) at java.lang.Thread.run(Thread.java:833)

**Comment by ghost** [comment] 2022-09-14 14:09
> A [comment on Curse](https://www.curseforge.com/minecraft/mc-mods/origins?comment=3623) leads me to wonder whether this is caused specifically by selected origins that alter player size. It would certainly match up with my own experience getting this crash, as all of the origins I'd personally tried from Bucolic Origins do indeed have size alterations, but I have yet to test more extensively with origins that don't do anything with the player's size
> 
> Could anyone else who has had this issue perhaps clarify what origin datapack/addon they are using/getting the crash with, as well as whether the origin selected that causes the crash alters player size in any way?
> 
> Quoting the comment itself for ease of access:
> 
> > playing on 1.19.2 works fine but any origin that changes size causes this error, causing any server (singleplayer or dedicated) to crash, yes i have pehkui
> 
> > Description: Exception in server tick loopDescription: Exception in server tick loop
> > java.lang.NoSuchMethodError: 'int net.minecraft.class_2170.method_9249(net.minecraft.class_2168, java.lang.String)' at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.8) at io.github.apace100.apoli.power.factory.action.EntityActions.lambda$register$15(EntityActions.java:235) at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41) at io.github.apace100.origins.power.OriginsCallbackPower.onChosen(OriginsCallbackPower.java:24) at io.github.apace100.origins.component.OriginComponent.lambda$onChosen$0(OriginComponent.java:49) at java.lang.Iterable.forEach(Iterable.java:75) at io.github.apace100.origins.component.OriginComponent.onChosen(OriginComponent.java:49) at io.github.apace100.origins.networking.ModPacketsC2S.lambda$chooseOrigin$0(ModPacketsC2S.java:50) at net.minecraft.server.ServerTask.run(ServerTask:18) at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:776) at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:159) at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:758) at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:752) at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:140) at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:737) at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:669) at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257) at java.lang.Thread.run(Thread.java:833)

it's because the only way of changing player size is doing the /scale command

**Comment by eggohito** [comment] 2023-07-24 19:11
A bit late, but this should now be fixed in Origins 1.7.0

**Closed as completed by eggohito** 2023-07-24 19:11 UTC
Labels: bug
