### ISSUE TITLE
1.20.4 Update?

### ISSUE THREAD

**Issue by JTModel3** [apace100/origins-fabric#732] opened 2024-03-01 01:56 UTC
Howdy, it appears that there is some ground work for a 1.20.4 update but upon building and running, in the IDE it fails to run client and after building then placed into a regular Minecraft fabric instance it fails on world creation. Is there any hope of getting a working 1.20.4 version? Thank you.

**Comment by eggohito** [comment] 2024-03-04 06:23
The crash is probably caused by Reach Entity Attributes, since it was outdated at the time of the initial port to 1.20.4. Since my PR for updating Reach Entity Attributes has been merged since a while ago, you can use that in your fork (no need to change repositories, it's already published in their maven.)

But in the meantime, there is no ETA as to when the port will be continued, and I can't really work on it right now considering that there is a planned minor release

**Comment by BJT207** [comment] 2024-03-21 04:04
I came across this while debugging my load order. I thought it was a shot in the dark but I had ready ported all my other mods to 1.20.4 and figured it was worth trying. Low and behold, it worked! I updated Reach Entity Attributes to the latest version and compiled from source. As far as i can tell, everything is working fine now, with the only bug I've encountered so far being an annoying black screen flicker effect that goes away by disabling V-sync

**Closed as completed** 2024-11-03 15:26 UTC
