### ISSUE TITLE
lost connection: Invalid player data NEW GAME MODPACK server

### ISSUE THREAD

**Issue by popogamer** [apace100/origins-fabric#704] opened 2023-10-14 11:20 UTC
Im using this [modpack](https://www.curseforge.com/minecraft/modpacks/new-game-modpack-release) with his own server built but when i attempt to connetc ir says lost connection: Invalid player data and kick me out.

[log](https://mclo.gs/25pE7k7)

plz help

**Comment by eggohito** [comment] 2023-10-15 07:42
You seem to be using the unofficial Forge port of Origins. This issue tracker is for the official version of Origins, which is for Fabric. The issue doesn't seem to be caused by Origins at all, but more so by the Falling Tree mod, so try removing that mod and see if the issue still persists.

I'll be closing this issue, since it's not related to the official version of Origins nor Origins in general

**Closed by eggohito** 2023-10-15 07:42 UTC
