### ISSUE TITLE
Elytrian launching feature launching way to high

### ISSUE THREAD

**Issue by PixelatedBruh** [apace100/origins-fabric#2] opened 2020-07-11 06:10 UTC
When testing this mod the Elytrian ability launches me upwards nonstop till the game crashes. It seams to be exponentially going up as well. I do not think this is intended behavior.

edit it appears to only happen when you use it mid flight.

**Comment by apace100** [comment] 2020-07-11 07:12
Hey there,

I sadly couldn't reproduce your problem. Do you have any more information? E.g. do you have other mods installed, or do you have a log file I could take a look at?

**Comment by PixelatedBruh** [comment] 2020-07-12 05:56
Weird enough It seam to stop happening after switching worlds and no It was just this mod. So I really don't know what it was either. probably a freak bug on minecrafts part?

**Comment by apace100** [comment] 2020-07-12 12:40
Okay, glad to hear it's not a problem anymore! I'm gonna close this issue then. :)

**Closed by apace100** 2020-07-12 12:40 UTC
