### ISSUE TITLE
Phantom suffocates in blocks with Lithium installed

### ISSUE THREAD

**Issue by qapleulia** [apace100/origins-fabric#473] opened 2021-12-13 22:55 UTC
Lithium version 1.18.1-0.7.6
Origins version 1.8 1.3.1

Let me know if any other info is needed I am not the most technically minded 😔

**Comment by eggohito** [comment] 2021-12-15 01:44
~~I believe this has been fixed in the latest `dev` build of Lithium~~

**Comment by RabbyDevs** [comment] 2021-12-18 11:56
Where can I find this dev build?

**Comment by eggohito** [comment] 2021-12-19 14:36
It was due to Lithium's new rule for optimizing entity suffocation checks.

To disable this new optimization rule, you can set the value of the `mixin.entity.collisions.suffocation` rule in the `lithium.properties` file from your Minecraft's (or server) `config` folder to `false`, like so:
```properties
# This is the configuration file for Lithium.
# This file exists for debugging purposes and should not be configured otherwise.
#
# You can find information on editing this file and all the available options here:
# https://github.com/jellysquid3/lithium-fabric/wiki/Configuration-File
#
# By default, this file will be empty except for this notice.
mixin.entity.collisions.suffocation=false
```

**Comment by Gyration51** [comment] 2022-02-07 23:04
And how would one access said config folder to change said folder to false?

**Comment by ThePhantomPig791** [comment] 2022-02-08 00:08
> And how would one access said config folder to change said folder to false?

The filepath would be: .minecraft/config/lithium.properties
If it's on a server, swap out .minecraft with the server folder

**Comment by Neaft** [comment] 2022-06-14 19:58
> mixin.entity.collisions.suffocation=false
>
What should I do if I'm playing on LAN ?

**Comment by eggohito** [comment] 2022-06-14 21:34
> > mixin.entity.collisions.suffocation=false
> 
> What should I do if I'm playing on LAN ?

In that case, the LAN host would have to modify the configuration file for Lithium on their end

**Comment by SirGoldenTaco** [comment] 2022-06-26 22:24
I can confirm that in lan it doesn't seem to work

Any solutions?

**Comment by ChristianKilduff** [comment] 2022-07-01 10:26
> I can confirm that in lan it doesn't seem to work
> 
> 
> 
> Any solutions?

the lan host is basically the server host, so if the owner of the lan server changes the config in his files it should work

**Comment by SirGoldenTaco** [comment] 2022-07-01 18:22
Yeah I'm the host and the file looks like this

https://pastebin.com/QEnXCwpv

But whenever I'm in walls it still hurts me

**Comment by CriticalMichael** [comment] 2022-08-14 03:36
I was having the same problem after downloading the [Medieval MC Modpack](https://www.curseforge.com/minecraft/modpacks/medieval-mc-fabric) through the curseforge app. I even went into User>Twitch>Minecraft>instances>Medieval Fabric [FABRIC] 1.19 & 1.18.2>Config>lithium.properties and added mixin.entity.collisions.suffocation=false to line 8. It's works! Leaving this here incase anyone else is confused about the filepath if you're using curseforge. Also, you can do this while the game is running, but it won't work until you close the game and rerun it.

**Comment by eggohito** [comment] 2023-07-24 19:09
As of Origins 1.9.0, the `mixin.entity.collisions.suffocation` optimization rule should now be automatically disabled if Lithium is installed alongside Origins/Apoli

**Closed as completed by eggohito** 2023-07-24 19:09 UTC
Labels: bug, compatibility

**Comment by Lichofhearts** [comment] 2024-02-01 01:28
I take damage even though I do not have lithium. Any other mods known to cause problems?
