### ISSUE TITLE
Being underground then mining a hole above you protects Blazeborn from rain damage in that spot

### ISSUE THREAD

**Issue by The-Fireplace** [apace100/origins-fabric#31] opened 2020-09-05 01:02 UTC
![2020-09-04_19 53 52](https://user-images.githubusercontent.com/5914284/92293354-8e925700-eee8-11ea-8bc1-8908eb8f29dc.png)
Origins 1.16.2-0.3.7
To reproduce:
1. Be Blazeborn
2. Wait until it rains
3. Go underground and dig straight up
4. See that the rain doesn't injure you unless you tower up to ground level. Even when you tower up until it's a one block hole, you're protected.

Other note: Being above ground and digging a one block hole doesn't protect you like digging up from below does

**Comment by apace100** [comment] 2020-10-19 18:44
Hey. I did not investigate this bug until now because it basically used Vanilla behaviour for detecting whether the player is in rain and I did not expect I could do something about it.

Going through the issues now, I decided to try to reproduce it. At least in the newest version, 0.4.0, I did not manage to reproduce this bug. So either something on Mojang's side or something on my side changed, either way, the bug does not seem to exist anymore. Let me know if you're still experiencing this issue on the newer versions of Origins. I'm closing this issue for now.

**Closed by apace100** 2020-10-19 18:44 UTC
