### ISSUE TITLE
Server stuck - Game breaking bug

### ISSUE THREAD

**Issue by serioos** [apace100/origins-fabric#454] opened 2021-11-08 14:17 UTC
The multiplayer server goes into a coma on start up and gets stuck on loading in the new update.

Origins 1.1.4.
Fabric API 0.42.1
Fabric Loader 12.5

And it gets stuck on start_remnant_gamerule not being defined even though requiem has never been installed on it at any point in time. 

Here's the log:

https://pastebin.com/3JUJPAi3

**Comment by eggohito** [comment] 2021-11-10 06:50
Do you have any datapacks in the server?

**Comment by serioos** [comment] 2021-11-10 08:58
There's no datapacks. But there are other mods. Here's the list:

https://pastebin.com/VE5FRXvE

**Comment by apace100** [comment] 2021-11-11 20:04
This issue is caused by Rat's Mischief, but has been fixed in their latest version (1.3.1).
If you update, the problem should be gone.
If the problem still persists after updating, please open an issue on their issue tracker, and don't forget specifying that you're on the latest version. :D

Rat's Mischief issue tracker: https://github.com/Ladysnake/Rats-Mischief/issues

**Closed as completed by apace100** 2021-11-11 20:04 UTC
