### ISSUE TITLE
Enderieans should be harmed by water bottles, splash potions of water, lingering water potions and water filled cauldrons  

### ISSUE THREAD

**Issue by 0-Red** [apace100/origins-fabric#212] opened 2021-03-17 21:27 UTC
i noticed this and i think its dumb that they are not damaged by the water in potions and water filled cauldrons.

**Comment by MineRobber9000** [comment] 2021-03-27 13:35
possible duplicate of #202?

**Comment by apace100** [comment] 2021-04-18 14:40
Water-filled cauldrons do not affect the hydrophobic origins because they are not considered by Minecraft to be filled with water. This is also why breathing in them does not work as a Merling. I have no intention to change this because I want to stay consistent with the vanilla mechanics of the cauldron (should vanilla change this at some point, I will too).

Drinking water bottles hurts the hydrophobic origins since version 0.7.0. I will look into the other potions, but for that I will leave the other issue MineRobber9000 linked open and close this one since it's a duplicate.

**Closed by apace100** 2021-04-18 14:40 UTC
